### ISSUE TITLE
Could not meet dependency requirements using conda package manager

### ISSUE THREAD

**Issue by eohulse** [marcoaaguiar/yaocptool#26]
I know it is indicated to use pip to install this package, but today is also very common to use conda as package manager to python, and also so setup environments.

When trying to use conda to install the dependencies for yaocptool I got some conflicting dependencies between them. More specifically,
- casadi is available through the "conda-forge" channel, but is only available for python2.7, 3.5 or 3.6
- sobol_seq is available only through "https://conda.binstar.org/naught101" channel, but requires python3.4

Maybe I am missing something, but anyway could you please provide a manner to install this package through conda?

**Comment by marcoaaguiar** [comment]
Only PyPI (pip) support is intended. Ask upstream to for them to post in conda-forge.
Closing issue
